language: r
sudo: required
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_binary_packages:
  - rgdal

r_github_packages:
  - rstudio/rmarkdown
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
